---
- name: Harden the bastion host
  hosts: bastion
  become: true
  gather_facts: true

  roles:
    - role: security
    - role: proxy

- name: Configure and deploy the AgriPulse application server
  hosts: app
  become: true
  gather_facts: true

  roles:
    - role: docker
    - role: app
    - role: security
